apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-predictor
  namespace: chrunemodel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-predictor
  template:
    metadata:
      labels:
        app: churn-predictor
    spec:
      containers:
      - name: churn-predictor
        image: vishnu4538/churn-predictor:v1
        ports:
        - containerPort: 8000
